version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

  nats:
    image: nats:alpine
    container_name: nats
    expose:
      - "4222"
      - "8222"
    ports:
      - "4222:4222"   # Expose NATS port
      - "8222:8222"   # Expose WebSocket port
    volumes:
      - ./nats-configure.conf:/etc/nats/nats-server.conf
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    restart: unless-stopped

  backend-redis:
    image: golang:latest
    container_name: backend-redis
    command: ["sh", "-c", "cd /app && ./bkend-redis"]
    volumes:
      - ./build:/app
      - ./bkend-redis/configs:/app/configs
    ports:
      - 8003:8003
    depends_on:
      - redis
    restart: unless-stopped

  backend-db:
    image: golang:latest
    container_name: backend-db
    command: ["sh", "-c", "cd /app && ./bkend-db"]
    volumes:
      - ./build:/app
      - ./bkend-db/configs:/app/configs
    ports:
      - 8004:8004
    depends_on:
      - mongo
    restart: unless-stopped

  backend:
    image: golang:latest
    hostname: backend
    command: ["sh", "-c", "cd /app && ./bkend"]
    volumes:
      - ./build:/app
      - ./bkend/configs:/app/configs
    expose:
      - "8000"
    depends_on:
      - backend-db
      - backend-redis
      - nats
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
